In [1]:
import numpy as np

# 1.Extract even numbers  from 1D array

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 0]

array([0, 2, 4, 6, 8])

# 2.How to create a 2D array containing random floats between 5 and 10?

In [3]:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

[[8.77438241 8.74134211 7.01996278]
 [7.13760057 9.14756222 9.27380467]
 [6.93632607 5.9120629  9.0456884 ]
 [6.51136438 6.19803287 6.83504686]
 [8.33714249 5.23340318 8.49569324]]


In [4]:
a = np.linspace(5,10,4).reshape(2,2)
print('2D Array:','\n',a)


2D Array: 
 [[ 5.          6.66666667]
 [ 8.33333333 10.        ]]


# 3.How to print only 3 decimal places in python numpy array

In [5]:
rand_arr =np.round(np.random.random((5,3)),decimals=3)
rand_arr

array([[0.332, 0.13 , 0.093],
       [0.561, 0.651, 0.251],
       [0.265, 0.776, 0.709],
       [0.299, 0.908, 0.245],
       [0.26 , 0.66 , 0.517]])

# 4.Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [6]:
v = np.arange(15,56)
print("Original vector:")
print(v)
print("All values except the first and last of the said vector:")
print(v[1:-1])

Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


# 5.Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [7]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [8]:
a = np.zeros((5,5))
a[0,0]=1
a[1,1]=2
a[2,2]=3
a[3,3]=4
a[4,4]=5
print(a)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


# 6.Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros.

Change the said array in the following format:

Given array:

[[0 0 0 0 0 0]

[0 0 0 0 0 0]

[0 0 0 0 0 0]

[0 0 0 0 0 0]

[0 0 0 0 0 0]]

New array:

[[3 0 3 0 3 0]

[7 0 7 0 7 0]

[3 0 3 0 3 0]

[7 0 7 0 7 0]

[3 0 3 0 3 0]]


In [10]:
nums = np.zeros(shape=(5, 6), dtype='int')
print("Original array:")
print(nums)
nums[::2, ::2] = 3
nums[1::2, ::2] = 7
print("\nNew array:")
print(nums)

Original array:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

New array:
[[3 0 3 0 3 0]
 [7 0 7 0 7 0]
 [3 0 3 0 3 0]
 [7 0 7 0 7 0]
 [3 0 3 0 3 0]]


# 7.Write a NumPy program to create a 4x4 array, now create a new array from the said array swapping first and last, second and third columns.

In [11]:
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last columns of the said array:")
new_nums = nums[:, ::-1]
print(new_nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last columns of the said array:
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


# 8.Write a NumPy program to swap rows and columns of a given array in reverse order.

In [12]:
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
print("Original array:")
print(nums)
print("\nSwap rows and columns of the said array in reverse order:")
new_nums = print(nums[::-1, ::-1])
print(new_nums)

Original array:
[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]

Swap rows and columns of the said array in reverse order:
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]
None


# 9.Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.

In [13]:
nums = np.array([[[1, 5, 2, 1],
               [4, 3, 5, 6],
               [6, 3, 0, 6],
               [7, 3, 5, 0],
               [2, 3, 3, 5]],
              
              [[2, 2, 3, 1],
               [4, 0, 0, 5],
               [6, 3, 2, 1],
               [5, 1, 0, 0],               
               [0, 1, 9, 1]],
              
              [[3, 1, 4, 2],
               [4, 1, 6, 0],
               [1, 2, 0, 6],
               [8, 3, 4, 0],               
               [2, 0, 2, 8]]]) 
print("Array:")
print(nums)

Array:
[[[1 5 2 1]
  [4 3 5 6]
  [6 3 0 6]
  [7 3 5 0]
  [2 3 3 5]]

 [[2 2 3 1]
  [4 0 0 5]
  [6 3 2 1]
  [5 1 0 0]
  [0 1 9 1]]

 [[3 1 4 2]
  [4 1 6 0]
  [1 2 0 6]
  [8 3 4 0]
  [2 0 2 8]]]


# 10.Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [14]:
x = np.random.random((3, 3, 3))
print(x)

[[[0.1747823  0.63064854 0.79100233]
  [0.18014902 0.30507615 0.86097434]
  [0.88223348 0.10758573 0.84911411]]

 [[0.90503762 0.00525736 0.20527095]
  [0.28142381 0.84489105 0.51567524]
  [0.42236042 0.22062434 0.05803134]]

 [[0.85464241 0.3532846  0.97069698]
  [0.05200606 0.21507778 0.82568329]
  [0.6516548  0.22094512 0.54031747]]]
